apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: healthsync
spec:
  type: LoadBalancer
  selector:
    app: appointment-service
  ports:
    - port: 80          # External port exposed by the LoadBalancer
      targetPort: 8000   # Correct internal port where the app is running
  selector:
    app: appointment-service   # Matches the label in the Deployment
